#!/bin/bash

# Just for fun :D
sudo apt-get install figlet

figlet basics

# Then install some basic stuff
echo "Start with the basics."
echo "Those packages are required by all libs."
sudo apt-get install git vim cmake pkg-config libgtk-3-dev python python-pip python-dev 

# Set Vim as editor for git
git config --global core.editor "vim"
git config --global diff.tool vimdiff
git config --global merge.tool vimdiff

