#!/bin/bash

cd $DIR

# Why not? :P
figlet opencv

# Compiler
sudo apt-get install build-essential

# Required
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev

# Optional
sudo apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

# Cloning repo
cd $DOWNLOAD_DIR
git clone https://github.com/opencv/opencv.git 
git clone https://github.com/opencv/opencv_contrib.git

# CMake dir
cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -D WITH_GSTREAMER=ON -D WITH_IPP=OFF -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D CMAKE_INSTALL_PREFIX=/usr/local ..

# Make and install
make -j2 # Number of threads
sudo make install

# Postinstall stuff
echo '/usr/local/lib' >> /etc/ld.so.conf.d/opencv.conf
sudo ldconfig -v
echo 'PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig' >> /etc/bash.bashrc
echo 'export PKG_CONFIG_PATH' >> /etc/bash.bashrc
